### ISSUE TITLE
Use unit classes instead of primitives

### ISSUE THREAD

**Issue by Loomie** [Baret/pltcmd#120] opened 2020-10-31 10:22 UTC
**Description**
This comes from a [review comment](https://github.com/Baret/pltcmd/pull/117#discussion_r510026484).

Most values have a specific unit in mind. For example `val distance: Long` stores the distance in meters or kilometers. But that is not expressed in the code. For easy recognition of what is meant and to extend specific use cases a named class should be used. Beside fields these new classes should also be used as return values and may improve local variable usage.

**Implementation details**
[Inline classes](https://kotlinlang.org/docs/reference/inline-classes.html) can be used to prevent un-/wrapping the values for all those data operations.

**Comment by Baret** [comment] 2022-04-24 18:12
Duplicate of #146 and already resolved by PR #148

**Closed by Baret** 2022-04-24 18:12 UTC
